site_name: Agentic-AI Documentation
site_description: Documentation for the Agentic-AI framework
site_author: Agentic-AI Team

docs_dir: documentation # Explicitly set the documentation directory

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Core Concepts:
      - Core AI: core.md
      - Agents: agents.md
      - Conversations: conversations/overview.md
      - Error Handling: error_handling.md
      - Configuration: configuration_system.md
  - Tools & MCP:
      - Overview: tools/overview.md
      - Using MCP Tools: examples/mcp_tool_usage.md
      - Tool Statistics: examples/tool_stats_example.md
  - Utilities:
      - Logging & Utils: utils.md
      - Prompt Management: prompt_templates/management.md
      - Prompting Guide: prompt_templates/guide.md
      - Metrics System: metrics_system.md
  - Models:
      - Overview: providers/overview.md
  - Examples:
      - Overview: examples.md
      - Configuration: examples/configuration_example.md
      - UI: ui/gradio_interface.md
      - Testing:
          - Testing Providers: development/testing_providers.md
          - Testing Strategy: development/testing_strategy.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - admonition

  

plugins:
  - search

repo_url: https://github.com/0x00000002/agentic-ai
site_url: https://0x00000002.github.io/agentic-ai/