# Agent configuration

# Agent descriptions for AI prompting and routing
agent_descriptions:
  base: "A general-purpose agent that can handle simple requests and provide information."
  listener: "Handles audio processing and speech recognition"
  translator: "Translates between languages"
  website_parser: "Searches websites for information"
  content_generator: "Creates multimedia content (images, videos, audio)"
  action_planner: "Breaks complex tasks into subtasks"
  mcp_searcher: "Finds relevant Model-Centric Processes"
  paralleliser: "Executes tasks in parallel"
  tool_finder: "Identifies relevant tools for user requests"
  coordinator: "Routes requests to appropriate specialized agents"
  request_analyzer: "Analyzes requests to determine appropriate agents and tools"
  response_aggregator: "Aggregates responses from multiple agents"
  coding_assistant: "Assists with coding tasks, debugging, and explanations."
agents:  
  # --- Renamed Coordinator Configuration ---
  coordinator:
    description: "Coordinates the workflow between specialized agents based on request analysis."
    max_parallel_agents: 1 
    default_handler_agent: "chat_agent"
  # --- End Coordinator Configuration ---
  
  # --- Chat Agent Configuration --- 
  chat_agent: # Must match default_handler_agent above
     description: "A general conversational agent for handling simple questions or acting as a fallback."
     default_model: "gpt-4o-mini" 
     system_prompt: "You are a helpful general-purpose assistant." 
  # --- End Chat Agent Configuration ---

  # Listener agent configuration
  listener:
    default_model: "gpt-4o-mini"
    system_prompt: "You are an expert at processing and understanding audio content."
    language_detection: true
    speaker_diarization: false
    emotion_detection: false
    supported_formats:
      - wav
      - mp3
      - m4a
      - ogg
  
  # Translator agent configuration
  translator:
    default_model: "gpt-4o-mini"
    system_prompt: "You are an expert translator who preserves context and meaning across languages."
    default_translation_engine: "openai"
    supported_languages:
      - en
      - es
      - fr
      - de
      - it
      - pt
      - ru
      - zh
      - ja
      - ko
  
  # Website Parser agent configuration
  website_parser:
    default_model: "claude-3-haiku"
    system_prompt: "You are an expert at finding and extracting relevant information from websites."
    max_pages: 5
    max_depth: 3
    relevance_threshold: 0.7
    respect_robots_txt: true
    timeout_seconds: 60
  
  # --- Comment out or remove old Orchestrator config if no longer needed ---
  # orchestrator:
  #   description: "Coordinates the workflow between specialized agents."
  #   default_model: "gpt-4o" 
  #   system_prompt: "You are an expert at breaking complex tasks into well-defined subtasks."
  #   max_subtasks: 10
  #   max_parallel_agents: 3
  #   planning_depth: 3
  #   min_subtask_size: 1
  # --- End Old Orchestrator Config ---

  # Content Generator agent configuration
  content_generator:
    default_model: "gpt-4o-mini"
    system_prompt: "You are an expert at creating high-quality content based on user specifications."
    supported_formats:
      - image
      - audio
      - video
      - diagram
    default_providers:
      image: "dalle3"
      audio: "elevenlabs"
      video: "runway"
      diagram: "mermaid"
  
  # MCP Searcher agent configuration
  mcp_searcher:
    default_model: "gpt-4o-mini"
    system_prompt: "You are an expert at finding and utilizing Model-Centric Processes (MCPs)."

  # Tool Finder agent configuration
  tool_finder:
    default_model: "claude-3-haiku"
    system_prompt: "You are an expert at identifying relevant tools for user requests."
    confidence_threshold: 0.6

  # Request Analyzer agent configuration  
  request_analyzer:
    description: "Analyzes user requests to determine intent, use case, and assign agents/tools."
    default_model: "gpt-4o-mini"
    system_prompt: "You are an expert at analyzing user requests and determining appropriate agents."
    confidence_threshold: 0.6
    
  # Response Aggregator agent configuration
  response_aggregator:
    description: "Aggregates responses from multiple agents into a unified answer."
    default_model: "claude-3-5-sonnet" # Use the key defined in models.yml
    system_prompt: "You are an expert at combining multiple responses into a coherent whole."

  # Add configurations for other agents...
  coding_assistant:
    description: "Assists with coding tasks, debugging, and explanations."
    default_model: "gpt-4o" # Use gpt-4o

  solidity_expert:
    description: "Provides expertise in Solidity smart contracts and blockchain security."
    default_model: "gpt-4o" # Use gpt-4o

  content_creator:
    description: "Generates creative content like articles, stories, or marketing copy."
    default_model: "claude-3-5-sonnet" # Use a valid key from models.yml 