providers:
  anthropic:
    api_key_env: ANTHROPIC_API_KEY
    timeout: 30
  openai:
    api_key_env: OPENAI_API_KEY
    timeout: 30
  ollama:
    api_key_env: OLLAMA_API_KEY
    base_url: http://localhost:11434
    timeout: 30
  gemini:
    api_key_env: GOOGLE_API_KEY
    timeout: 30

models:
  claude-3-7-sonnet:
    name: "Claude 3.7 Sonnet"
    model_id: claude-3-7-sonnet-20250219
    provider: anthropic
    privacy: EXTERNAL
    quality: HIGH
    speed: FAST
    max_tokens: 4096
    temperature: 0.7
    cost:
      input_tokens: 0.000003  # $0.000003 per input token
      output_tokens: 0.000015  # $0.000015 per output token
      minimum_cost: 0.0001  # Minimum cost per request
  claude-3-5-sonnet:
    name: "Claude 3.5 Sonnet"
    model_id: claude-3-5-sonnet-latest
    provider: anthropic
    privacy: EXTERNAL
    quality: MEDIUM
    speed: FAST
    max_tokens: 4096
    temperature: 0.7
    cost:
      input_tokens: 0.000003  # $0.000003 per input token
      output_tokens: 0.000015  # $0.000015 per output token
      minimum_cost: 0.0001  # Minimum cost per request
  claude-3-5-haiku:
    name: "Claude 3.5 Haiku"
    model_id: claude-3-5-haiku-latest
    provider: anthropic
    privacy: EXTERNAL
    quality: LOW
    speed: FAST
    max_tokens: 4096
    temperature: 0.7
    cost:
      input_tokens: 0.000001  # $0.000001 per input token
      output_tokens: 0.000005  # $0.000005 per output token
      minimum_cost: 0.0001  # Minimum cost per request
  o3-mini:
    name: "ChatGPT O3 Mini"
    model_id: o3-mini-2025-01-31
    provider: openai
    privacy: EXTERNAL
    quality: HIGH
    speed: FAST
    max_tokens: 4096
    temperature: 0.7
    cost:
      input_tokens: 0.00001  # $0.00001 per input token
      output_tokens: 0.00003  # $0.00003 per output token
      minimum_cost: 0.0001  # Minimum cost per request
  gpt-4o-mini:
    name: "ChatGPT 4o Mini"
    model_id: gpt-4o-mini
    provider: openai
    privacy: EXTERNAL
    quality: MEDIUM
    speed: FAST
    max_tokens: 4096
    temperature: 0.7
    cost:
      input_tokens: 0.0000005  # $0.0000005 per input token
      output_tokens: 0.0000015  # $0.0000015 per output token
      minimum_cost: 0.0001  # Minimum cost per request
  gemma3:
    name: "Gemini Gemma 3"
    model_id: gemma3:27b
    provider: ollama
    privacy: LOCAL
    quality: MEDIUM
    speed: STANDARD
    max_tokens: 2048
    temperature: 0.7
    cost:
      input_tokens: 0  # Local models have no token cost
      output_tokens: 0
      minimum_cost: 0
  deepseek-32b:
    name: "DeepSeek R1 32B"
    model_id: deepseek-r1:32b
    provider: ollama
    privacy: LOCAL
    quality: MEDIUM
    speed: SLOW
    max_tokens: 2048
    temperature: 0.7
    cost:
      input_tokens: 0  # Local models have no token cost
      output_tokens: 0
      minimum_cost: 0
  qwq:
    name: "QWQ"
    model_id: qwq
    provider: ollama
    privacy: LOCAL
    quality: LOW
    speed: STANDARD
    max_tokens: 2048
    temperature: 0.7
    cost:
      input_tokens: 0  # Local models have no token cost
      output_tokens: 0
      minimum_cost: 0
  deepseek-7b:
    name: "DeepSeek R1 7B"
    model_id: deepseek-r1:7b
    provider: ollama
    privacy: LOCAL
    quality: LOW
    speed: STANDARD
    max_tokens: 2048
    temperature: 0.7
    cost:
      input_tokens: 0  # Local models have no token cost
      output_tokens: 0
      minimum_cost: 0
  gemini-2-5-pro:
    name: "Gemini 2.5 Pro"
    model_id: gemini-2.5-pro-exp-03-25
    provider: gemini
    privacy: EXTERNAL
    quality: HIGH
    speed: FAST
    max_tokens: 2048
    temperature: 0.7
    cost:
      input_tokens: 0.00000025  # $0.00025 per 1K characters
      output_tokens: 0.00000025  # $0.00025 per 1K characters
      minimum_cost: 0.0001  # Minimum cost per request
  gemini-1-5-pro:
    name: "Gemini 1.5 Pro"
    model_id: gemini-1.5-pro
    provider: gemini
    privacy: EXTERNAL
    quality: MEDIUM
    speed: FAST
    max_tokens: 2048
    temperature: 0.7
    cost:
      input_tokens: 0.00000025  # $0.00025 per 1K characters
      output_tokens: 0.00000025  # $0.00025 per 1K characters
      minimum_cost: 0.0001  # Minimum cost per request

# Default settings
default_model: claude-3-7-sonnet
log_level: INFO

# Use case specific configurations
use_cases:
  translation:
    quality: LOW
    speed: STANDARD
  coding:
    quality: HIGH
    speed: FAST
  solidity_coding:
    quality: HIGH
    speed: STANDARD
  chat:
    quality: MEDIUM
    speed: STANDARD
  content_generation:
    quality: MEDIUM
    speed: STANDARD
  data_analysis:
    quality: HIGH
    speed: SLOW
  web_analysis:
    quality: MEDIUM
    speed: STANDARD
  image_generation:
    quality: HIGH
    speed: SLOW 