# src/config/tools.yml
# Defines internal tools or wrappers for external APIs managed within this project.

tools:
  # Core utility tools
  - name: "get_current_datetime"
    description: "Get the current date and time in ISO 8601 format."
    module: "src.tools.core.datetime_tool" 
    function: "get_datetime"              
    parameters_schema: {}                  
    category: "core_utils"
    source: "internal"
    speed: "instant"
    safety: "native"

  - name: "calculator"
    description: "Perform mathematical calculations. Input should be a valid mathematical expression string (e.g., '2 * (3+4)'). Uses asteval for safe evaluation."
    module: "src.tools.core.calculator_tool"
    function: "calculate"
    parameters_schema:
      type: "object"
      properties:
        expression:
          type: "string"
          description: "The mathematical expression to evaluate (e.g., '2 + 2 * 5')."
      required: ["expression"]
    category: "core_utils"
    source: "internal"
    speed: "fast"
    safety: "sandboxed"

  # We can add the dummy tool here if needed for testing/demo
  - name: "dummy_tool"
    description: "A simple built-in tool for demonstration and testing purposes."
    module: "src.tools.core.dummy_tool"
    function: "dummy_tool_function"
    parameters_schema:
      type: "object"
      properties:
        query: 
          type: "string"
          description: "The input query for the dummy tool."
      required: ["query"]
    category: "built_in"
    source: "internal"
    speed: "fast"
    safety: "native"

  # Media generation tools
  - name: "generate_image"
    description: "Generates an image from a text description using the latest Stable Diffusion 3.5 Medium model via Replicate API. Use this tool when asked to create, draw, or generate an image."
    module: "src.tools.media.image_generator"
    function: "generate_image"
    parameters_schema:
      type: "object"
      properties:
        prompt:
          type: "string"
          description: "Description of the image to generate"
        negative_prompt:
          type: "string"
          description: "Elements to avoid in the generated image"
        width:
          type: "integer"
          description: "Image width (used to approximate aspect_ratio if aspect_ratio kwarg not provided)"
          default: 1024
        height:
          type: "integer"
          description: "Image height (used to approximate aspect_ratio if aspect_ratio kwarg not provided)"
          default: 1024
        num_inference_steps:
          type: "integer"
          description: "Number of denoising steps (passed as 'steps' to API)"
          default: 40 # Default for SD 3.5 Medium
        # Optional kwargs like aspect_ratio, output_format, output_quality, cfg can be passed via **kwargs
      required: ["prompt"]
    category: "media"
    source: "internal"
    speed: "medium"
    safety: "external"

# Built-in tools configuration
built_in:
  enabled: true
  
# Tool execution settings
execution:
  timeout: 360  # Increased timeout to 6 minutes for slow tools like image gen
  max_retries: 3
  
# Tool statistics settings
stats:
  storage_path: "data/tool_stats.json"
  track_usage: true
  
# Tools by category
categories:
  file_management:
    description: "Tools for managing files and directories"
    enabled: true
  data_processing:
    description: "Tools for processing and analyzing data"
    enabled: true
  api_integration:
    description: "Tools for integrating with external APIs"
    enabled: true
    
# Tool finder agent settings
finder_agent:
  enabled: true
  max_recommendations: 5
  use_history: true 